name = "GraphVisualization"
uuid = "598cd8ba-da52-4789-a7af-86c7b9d84244"
authors = ["Nagefire <nagefire.dev@gmail.com>"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
